"""Lesson 9b — Question pool generator.

WHAT this does
==============
Generates a diverse list of questions to feed to `synthesis/generate.py`.
Uses Gemini 2.5 Flash (cheap) because the questions are just inputs
to Monty — the persona voice is generated by `generate.py` using
Gemini 2.5 Pro on top of these.

OUTPUT
======
`data/interim/question_pool.jsonl` — one JSON object per line, schema
`{"question": str}`. Consumed by:

    uv run python -m synthesis.generate --questions-file data/interim/question_pool.jsonl --count 1000

DESIGN
======
Ten topical categories, ~`count / 10` questions each, asked in
parallel via async Gemini calls. Categories cover the range of
behaviors the persona prompt targets:

  - tech opinions / recommendations
  - factual questions (geography, history, science)
  - life decisions (career, relationships, money)
  - emotional / ambiguous prompts (sharing news, processing)
  - venting (the "oh we fucking hate him" carve-out)
  - banter / vibe-checks
  - ask-back triggers (vague problems, "I'm thinking of X")
  - beginner technical ("what even is X")
  - opinion questions with no clean answer
  - specific situations needing concrete advice

Roughly even distribution. We dedupe (exact-match, lowercased)
before writing, then shuffle so the synth run doesn't do all
tech-then-all-life in order.

COST
====
~10 Gemini Flash calls, each ~5K output tokens. At Flash pricing
(~$0.30/1M output) this is ~$0.02 per 1,000 questions. Negligible.

Run:
    uv run python -m synthesis.question_pool                 # default: 1000
    uv run python -m synthesis.question_pool --count 100     # small pilot
"""
from __future__ import annotations

import argparse
import asyncio
import json
import os
import random
from pathlib import Path

from dotenv import load_dotenv
from google import genai
from google.genai import types

load_dotenv()

# ----- Model / paths -----
MODEL_ID = "gemini-2.5-flash"   # cheap; questions are inputs, not training data
DEFAULT_COUNT = 1000
OUTPUT_PATH = (
    Path(__file__).resolve().parent.parent
    / "data" / "interim" / "question_pool.jsonl"
)

# Concurrency cap — Flash tolerates higher than Pro.
MAX_CONCURRENT = 10

# Ten topical categories. Roughly even distribution across these gives
# the persona a balanced training corpus.
CATEGORIES: list[str] = [
    "tech opinions and recommendations — programming languages, "
    "frameworks, databases, tools, dev practices, build vs buy",

    "factual questions — geography, history, science, language, "
    "everyday facts a curious person might ask",

    "life decisions — career changes, relationships, money, big "
    "moves, whether to do or not do something significant",

    "emotional or ambiguous prompts — someone sharing news, "
    "processing something, telling you about their day in a way "
    "that's not quite a direct question",

    "venting about people — managers, colleagues, family members, "
    "partners, strangers, landlords, institutions; the asker is on "
    "their side and looking for solidarity",

    "banter / vibe-checks / sharing silly things — memes, dumb "
    "observations, sharing a cat picture, expressing exhaustion, "
    "low-stakes back-and-forth",

    "ask-back triggers — vague problem statements like 'I'm thinking "
    "of quitting' or 'something weird is happening with my mum' "
    "that need more context before a useful answer",

    "beginner technical questions — 'what even is X', 'how does Y "
    "actually work', 'why does my code do this' from someone new "
    "to the topic and not embarrassed to ask",

    "opinion questions with no clean answer — tabs vs spaces, "
    "Postgres vs Mongo, Vim vs Emacs, hot takes the asker actually "
    "wants the friend's view on",

    "specific situations needing concrete advice — fix this bug, "
    "draft this email, how should I phrase this to my boss, "
    "what's a reasonable counter-offer",
]

CATEGORY_PROMPT_TEMPLATE = """You are generating a list of realistic
questions that a person might text to a smart, opinionated friend.
The friend will reply later in a casual, witty voice — but your job
is to generate the questions only, not the answers.

Generate {n} questions covering this category:

  {category}

Rules:
- Each question is on its own line. No numbering. No bullets. No
  blank lines between. No explanations or category headers.
- The questions should sound like REAL things people text or ask
  their friends — not survey questions, not "as an AI" framings,
  not interview prompts.
- Mix lengths: some are 3-word questions ("postgres or mongo?"),
  some are 20-word ramblings ("ok so I might have just told my
  manager I'd take on the migration project but I have no idea
  what I'm doing").
- Mix register: some serious, some banter, some genuinely confused.
- Lowercase / casual punctuation is fine, matching how people text.
  Some questions can be properly punctuated too — variety.
- No questions that would require fabricating dangerous advice
  (drug synthesis, weapons, fake medical diagnoses). Casual life
  stuff is fine including emotional / mental health topics.

Output exactly {n} questions, one per line, nothing else.
"""


# Gemini 2.5 Flash output max is ~8K tokens. Each question is
# ~10 tokens. Asking for more than ~600 in one call risks truncation.
# 200 is a safe per-call ceiling that leaves room for variability
# in question length.
PER_CALL_MAX = 200


def _parse_questions(text: str) -> list[str]:
    """Extract one question per non-empty line from a Flash response,
    stripping accidental bullets / numbering that models sometimes add."""
    questions: list[str] = []
    for raw in text.splitlines():
        line = raw.strip()
        if not line:
            continue
        for prefix in ("- ", "* ", "• "):
            if line.startswith(prefix):
                line = line[len(prefix):].strip()
                break
        if line and line[0].isdigit():
            for sep in (". ", ") ", " - "):
                if sep in line[:5]:
                    line = line.split(sep, 1)[1].strip()
                    break
        if len(line) < 4:
            continue
        questions.append(line)
    return questions


async def generate_chunk(
    client: "genai.Client",
    category: str,
    n: int,
    semaphore: asyncio.Semaphore,
) -> list[str]:
    """One Flash call for up to PER_CALL_MAX questions in one category."""
    prompt = CATEGORY_PROMPT_TEMPLATE.format(n=n, category=category)
    async with semaphore:
        try:
            response = await client.aio.models.generate_content(
                model=MODEL_ID,
                contents=prompt,
                config=types.GenerateContentConfig(temperature=1.0),
            )
        except Exception as e:
            print(f"  ERROR chunk category={category[:40]!r}: "
                  f"{type(e).__name__}: {e}")
            return []
    return _parse_questions(response.text or "")


async def generate_category(
    client: "genai.Client",
    category: str,
    n: int,
    semaphore: asyncio.Semaphore,
) -> list[str]:
    """Generate `n` questions for one category, chunked into multiple
    Flash calls so we don't hit the output-token cap. Chunks run in
    parallel (gated by the global semaphore)."""
    if n <= PER_CALL_MAX:
        return await generate_chunk(client, category, n, semaphore)

    # Split n into ceil(n / PER_CALL_MAX) batches of at most PER_CALL_MAX.
    n_full_batches, remainder = divmod(n, PER_CALL_MAX)
    batch_sizes = [PER_CALL_MAX] * n_full_batches
    if remainder:
        batch_sizes.append(remainder)

    tasks = [
        generate_chunk(client, category, batch_n, semaphore)
        for batch_n in batch_sizes
    ]
    results = await asyncio.gather(*tasks)
    flat: list[str] = []
    for batch in results:
        flat.extend(batch)
    return flat


async def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--count", type=int, default=DEFAULT_COUNT,
                    help=f"Target number of questions. Default: {DEFAULT_COUNT}.")
    ap.add_argument("--output", type=Path, default=OUTPUT_PATH,
                    help=f"Output JSONL path. Default: {OUTPUT_PATH}")
    args = ap.parse_args()

    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        raise SystemExit(
            "GEMINI_API_KEY not set. Add it to .env (see .env.example)."
        )

    client = genai.Client(api_key=api_key)

    # Ask each category for slightly more than count/N to allow for
    # dedup attrition.
    per_category = max(1, args.count // len(CATEGORIES) + 10)
    print(
        f"Generating ~{per_category} questions per category "
        f"× {len(CATEGORIES)} categories via {MODEL_ID}..."
    )

    semaphore = asyncio.Semaphore(MAX_CONCURRENT)
    tasks = [
        generate_category(client, cat, per_category, semaphore)
        for cat in CATEGORIES
    ]
    results = await asyncio.gather(*tasks)

    # Flatten + dedupe (exact match, case-insensitive).
    seen: set[str] = set()
    pool: list[str] = []
    for cat_questions in results:
        for q in cat_questions:
            key = q.lower()
            if key in seen:
                continue
            seen.add(key)
            pool.append(q)

    print(f"Collected {len(pool)} unique questions before trim.")

    # Shuffle so the synth run isn't ordered by category.
    random.shuffle(pool)

    # Trim to target count.
    pool = pool[:args.count]

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w") as f:
        for q in pool:
            f.write(json.dumps({"question": q}, ensure_ascii=False) + "\n")

    print(f"Wrote {len(pool)} questions to {args.output}")

    # Print a sample of 10 so you can eyeball
    print("\n--- Sample of 10 questions ---")
    for q in pool[:10]:
        print(f"  - {q}")


if __name__ == "__main__":
    asyncio.run(main())
